tensor_map:
  cell_dimensions:
    - 0.09
    - 0.09
    - 0.09
  origin:
    - 0
    - 0
    - 0
  distance_filter:
    min_distance: 0.05
    max_knn: 100
  sparse_voting:
    sigma: 0.3
    max_dist: 0.6
    max_knn: 100
  dense_voting:
    sigma: 0.3
    max_dist: 0.6
    max_knn: 2000
    obs_dir_offset: 0.3
  traversability:
    length: 0.7
    width: 0.6
    height: 0.5
    diameter: 0.921954452991486
    inflation: 0.05
    z_offset: 0.09
    min_saliency: 10
    max_slope: 0.785398185253143
    max_points_in_free_cell: 0
    min_free_cell_ratio: 0.95
    max_points_in_bounding_box: 100
    min_support_points: 100
cost_functions:
  saliency_factor: 1
  orientation_factor: 1
  distance_factor: 1
  heading_factor: 5
  max_slope: 0.785398185253143
  saliency_threshold: 20
  maximal_saliency: 500
