tensor_map:
  cell_dimensions:
    - 0.15
    - 0.15
    - 0.15
  origin:
    - 0
    - 0
    - 0
  distance_filter:
    min_distance: 0.015
    max_knn: 100
  sparse_voting:
    sigma: 0.6
    max_dist: 0.9
    max_knn: 200
  dense_voting:
    sigma: 0.6
    max_dist: 0.9
    max_knn: 5000
    obs_dir_offset: 0.5
  traversability:
    length: 0.7
    width: 0.6
    height: 0.5
    diameter: 0.921954452991486
    inflation: 0.10
    ground_buffer: 0.15
    min_saliency: 500
    max_slope: 0.785398185253143
    max_points_in_free_cell: 1
    min_free_cell_ratio: 0.95
    max_points_in_bounding_box: 100
    min_support_points: 100
cost_functions:
  saliency_factor: 0.1
  orientation_factor: 5
  distance_factor: 1
  heading_factor: 1
  max_slope: 0.785398185253143
  saliency_threshold: 10000
  maximal_saliency: 20000
path_execution:
  flippers_params:
    slope_threshold: 0.296705961227417
    flat_threshold: 0.0872664600610733
    approach_up_before: 5
    approach_up_after: 2
    approach_down_before: 1
    approach_down_after: 2
    convex_up_before: 2
    convex_up_after: 1
    convex_down_before: 2
    convex_down_after: 2
  execution_params:
    v_max_flat: 0.1
    w_max_flat: 0.3
    v_max_slope: 0.05
    w_max_slope: 0.075
    max_distance: 0.15
    ignore_radius: 0.25
